# #######################################################################################################
# Dummy file to overwrite the analogous file contained in the WAR and avoid possible deployment problems
# due to pointing to paths with incorrect or non-existent configuration files.
#
# The correct configuration file is the application-env.yml file contained in this same directory.
# #######################################################################################################
