export const FRONTERA_SEGREGATION_YEAR = 2007;
export const FRONTERA_DATASET_ID = 'MUN_FRONTERA';
export const OLD_FRONTERA_ID = 'MUN_FRONTERA_19120318';
export const NEW_FRONTERA_ID = 'MUN_FRONTERA_20070908';
