export const REPRESENTANTES_ELEGIDOS = 'REPRESENTANTES_ELEGIDOS';
export const REPRESENTANTES_ELEGIDOS_TYPES = [
    'CONSEJEROS_CONSEJERAS', 
    'DIPUTADOS_DIPUTADAS', 
    'SENADORES_SENADORAS', 
    'CONCEJALES_CONCEJALAS', 
    'DIPUTADOS_DIPUTADAS_AUTONOMICOS'
];