# ===================================================================
# Spring Boot configuration for the "env" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    datasource:
        url: jdbc:postgresql://FILL_HOST:FILL_PORT/FILL_DATABASE
        username: FILL_USER
        password: FILL_PASS
    jpa:
        show-sql: false
    mail:
        host: FILL_HOST
        port: FILL_PORT
        username: FILL_USER
        password: FILL_PASS


# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    mail: 
        from: FILL_EMAIL
        base-url: http://FILL_APPLICATION_URL 
  
# ===================================================================
# Application specific properties
# Add your own application properties here.
# ===================================================================

application:
    dataset:
        evolucionElectoral: FILL_EVOLUCION_ELECTORAL_DATASET #Required: path to evolucion electoral dataset. Example: /datasets/ISTAC/C00010A_000007/~latest.json
#    visualizer:
#        showHeader: FILL_SHOW_HEADER #NOT Required: show header. Boolean.
#        showRightsHolder: FILL_SHOW_RIGHTS_HOLDER #NOT Required: show rights holder. Boolean.
#        organisationUrn: FILL_ORGANIZATION_URN #NOT Required: organization urn. Example urn:sdmx:org.sdmx.infomodel.base.Agency=SDMX:AGENCIES(1.0).ISTAC
#    estaticos:
#        navbarUrl: FILL_NAVBAR_ENDPOINT #NOT Required: URL to navbar HTML
#        footerUrl: FILL_FOOTER_ENDPOINT #NOT Required: URL to footer HTML
    metadata:
        endpoint: FILL_COMMON_METADATA_ENDPOINT #Required: common metadata endpoint
        installationType: FILL_INSTALLATION_TYPE #Required: installation type
#        statisticalResourcesInternalKey: FILL_STATISTICAL_RESOURCES_INTERNAL_KEY #NOT Required: statistical resources internal key
#        statisticalResourcesExternalKey: FILL_STATISTICAL_RESOURCES_EXTERNAL_KEY #NOT Required: statistical resources external key
#        structuralResourcesInternalKey: FILL_STRUCTURAL_RESOURCES_INTERNAL_KEY #NOT Required: structural resources internal key
#        structuralResourcesExternalKey: FILL_STRUCTURAL_RESOURCES_EXTERNAL_KEY #NOT Required: structural resources external key
#        indicatorsInternalKey: FILL_INDICATORS_INTERNAL_KEY #NOT Required: indicators internal key
#        indicatorsExternalKey: FILL_INDICATORS_EXTERNAL_KEY #NOT Required: indicators external key
#        statisticalVisualizerKey: FILL_STATISTICAL_VISUALIZER_KEY #NOT Required: statistical visualizer key (external only)
#        statisticalVisualizerApiKey: FILL_STATISTICAL_VISUALIZER_API_KEY #NOT Required: statistical visualizer api key (external only)
#        permalinksEndpointKey: FILL_PERMALINKS_ENDPOINT_KEY #NOT Required: permalinks endpoint key (external only)
#        exportEndpointKey: FILL_EXPORT_ENDPOINT_KEY #NOT Required: export endpoint key (external only)
#        googleTrackingIdKey: FILL_GA_TRACKING_ID_KEY #NOT Required: google analytics tracking id key
        
# ===================================================================        
# Application debug properties
#
# Uncomment if debug mode needed
# ===================================================================

# debug
