# ===================================================================
# Spring Boot configuration for the "env" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    datasource:
        url: jdbc:postgresql://FILL_HOST:FILL_PORT/FILL_DATABASE
        username: FILL_USER
        password: FILL_PASS
    jpa:
        show-sql: false
    mail:
        host: FILL_HOST
        port: FILL_PORT
        username: FILL_USER
        password: FILL_PASS


# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    mail: 
        from: FILL_EMAIL
        base-url: http://FILL_APPLICATION_URL 
  
# ===================================================================
# Application specific properties
# Add your own application properties here.
# ===================================================================

application:
    endpoints:
        statisticalResources: FILL_STATISTICAL_RESOURCES_ENDPOINT #Required: statistical resources endpoint
        structuralResources: FILL_STRUCTURAL_RESOURCES_ENDPOINT #Required: structural resources endpoint
        statisticalVisualizer: FILL_STATISTICAL_VISUALIZER_ENDPOINT #Required: statistical visualizer endpoint
        permalinks: FILL_PERMALINKS_ENDPOINT #Required: permalinks endpoint
        export: FILL_EXPORT_ENDPOINT #Required: export endpoint
        indicators: FILL_INDICATORS_ENDPOINT #Required: indicators endpoint
#    dataset:
#        evolucionElectoral: FILL_EVOLUCION_ELECTORAL_DATASET #NOT Required: evolucion electoral dataset
    visualizer:
#        showHeader: FILL_SHOW_HEADER #NOT Required: show header
#        showRightsHolder: FILL_SHOW_RIGHTS_HOLDER #NOT Required: show rights holder
#        organisationUrn: FILL_ORGANIZATION_URN #NOT Required: organization urn
        installationType: FILL_INSTALLATION_TYPE #Required: installation type
#    estaticos:
#        navbarUrl: FILL_NAVBAR_ENDPOINT #NOT Required: URL to navbar HTML
#        footerUrl: FILL_FOOTER_ENDPOINT #NOT Required: URL to footer HTML
    analytics:
        googleTrackingId: FILL_GA_TRACKING_ID #Required: google analytics tracking id
        
# ===================================================================        
# Application debug properties
#
# Uncomment if debug mode needed
# ===================================================================

# debug
